# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: try all your chance
email: pcl@pclewis.com
description: > # this means to ignore newlines until "baseurl:"
  hi im pcl. let me tell you about computers and stuff
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.pclewis.com" # the base hostname & protocol for your site
twitter_username: _pcl
github_username:  pclewis

collections:
- comments

# Build settings
markdown: kramdown
